const roles = {
  '* schiavo(a) di fabri v* ': 0,
  '* schiavo(a) di fabri IV* ': 1,
  '* schiavo(a) di fabri iii* ': 2,
  '* schiavo(a) di fabri II* ': 3,
  '* schiavo(a) di fabri i* ': 4,
  '* Apprendista di fabri v* ': 5,
  '* Apprendista di fabri  IV* ': 6,
  '* Apprendista di fabri  III* ': 7,
  '* Apprendista di fabri  i* ': 8,
  '* Apprendista di fabri  i* ': 9,
  '* Esperto(a), sta imparando da fabri v* ': 10,
  '* Esperto(a), sta imparando da fabri IV* ': 11,
  '* Esperto(a), sta imparando da fabri iii* ': 12,
  '* Esperto(a), sta imparando da fabri ii* ': 13,
  '* Esperto(a), sta imparando da fabri i* ': 14,
  '* Master, fabri apprezza il l impegno V* ': 15,
  '* Master, fabri apprezza il l impegno IV* ': 16,
  '* Master, fabri apprezza il l impegno III* ': 17,
  '* Master, fabri apprezza il l impegno II* ': 18,
  '* Master, fabri apprezza il l impegno i* ': 19,
  '* Bomber v* 🦾': 20,
  '* Bomber IV* 🦾': 21,
  '* Bomber III* 🦾': 22,
  '* Bomber i* 🦾': 23,
  '* Bomber I* 🦾': 24,
  '* Studente di Fabri v* 🔮': 25,
  '* Studente di Fabri IV* 🔮': 26,
  '* Studente di Fabri III* 🔮': 27,
  '* Studente di Fabri i* 🔮': 28,
  '* Studente di Fabri i* 🔮': 29,
  '* Diplomato da Fabri v* 🏅': 30,
  '* Diplomato da Fabri IV* 🏅': 31,
  '* Diplomato da Fabri III* 🏅': 32,
  '* Diplomato da Fabri I* 🏅': 33,
  '* Diplomato da Fabri I* 🏅': 34,
  '* Università da fabri v* 💎': 35,
  '* Università da fabri IV* 💎': 36,
  '* Università da fabri III* 💎': 37,
  '* Università da fabri II* 💎': 38,
  '* Università da fabri I* 💎': 39,
  '* Pro di botwhaita v* 😼': 40,
  '* Pro di botwhaita iv* 😼': 41,
  '* Pro di botwhaita iii* 😼': 42,
  '* Pro di botwhaita i* 😼': 43,
  '*Pro di botwhaita 😼': 44,
  '* Super Pro V* 🎩': 45,
  '* Super Pro IV* 🎩': 46,
  '* Super Pro III* 🎩': 47,
  '* Super Pro II* 🎩': 48,
  '* Super Pro I* 🎩': 49,
  '* Legendary (a) v* 🛡️': 50,
  '* Legendary (a) IV* 🛡️': 51,
  '* Legendary (a) iii* 🛡️': 52,
  '* Legendary (a) ii* 🛡️': 53,
  '* Legendary (a) i* 🛡️': 54,
  '* Leeda v* 🏆': 55,
  '* Leedada IV* 🏆': 56,
  '* Leeda III* 🏆': 57,
  '* Leeda I* 🏆': 58,
  '* Leed i* 🏆': 59,
  '* Stelar v* ☄️': 60,
  '* Stectarlar IV* ☄️': 61,
  '* Stelar III* ☄️': 62,
  '* Estelar I* ☄️': 63,
  '* Stelar I* ☄️': 64,
  '* Top Astral V* ⚜️🔱': 65,
  '* Top Astral IV* ✜️🔱': 66,
  '* Top Astral III* ✜️🔱': 67,
  '* Top Astral I* ⚜️🔱': 68,
  '* Top Astral I* ⚜️🔱': 69,
  '👑 * Élite Global V * 🏁': 70,
  '👑 * Élite Global IV * 🏁': 75,
  '👑 * Élite Global III * 🏁': 80,
  '👑 * Élite Global II * 🏁': 85,
  '👑 * Élite Global I * 🏁': 90,
  '👑 * ∞ élite globale v * 💎🏁': 100,
  '👑 * ∞ Élite Global IV * 💎🏁': 140,
  '👑 * ∞ Élite Global III * 💎🏁': 180,
  '👑 * ∞ Élite Global I * 💎🏁': 250,
  '👑 * ∞ Élite Global I * 💎🏁': 300,
};

export function before(m) {
  const user = db.data.users[m.sender];
  const level = user.level;
  const role = (Object.entries(roles).sort((a, b) => b[1] - a[1]).find(([, minLevel]) => level >= minLevel) || Object.entries(roles)[0])[0];
  user.role = role;
  return !0;
}
